# Generated by Django 5.1.3 on 2024-12-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255, null=True, unique=True),
        ),
    ]
