# Generated by Django 5.1.3 on 2024-12-09 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_remove_member_member_id_member_id_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='final_app.member'),
        ),
    ]
