# Generated by Django 5.1.3 on 2024-12-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='schedule',
            field=models.DateField(),
        ),
    ]
